[project]
name = "buil-call-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "pydot>=4.0.1",
    "pyvis>=0.3.2",
    "rich>=14.3.2",
]
